### ISSUE TITLE
Poap data csv export bug

### ISSUE THREAD

**Issue by baerlux** [BanklessDAO/analytics#1]
@PaulApivat 
There is a mismatch in the column ENS name column in the community call poap CSVs.
The first line where the column header usually appears contains a ens name.
Consequently all ens names are shifted by one and don't map to the correct adresses.

_File Bankless DAO Community Call #6.csv_
`
"ID","Owner","shocktop.eth","Claim Date","Tx Count","Power"
"360744","0xdc99de2b50984269d5dd976766cad8d9eb9cff94","greggarner.eth","6/18/2021","1","29"
`

**Comment by PaulApivat** [comment]
Thanks for notifying @baerlux , i'll inform the POAP team in discord.

There's a similar issue for Community Call #1 (but oddly not for CC 2-5, for some reason).

Fortunately, the current analysis use non-identifying aggregate data, so I've cut out the ENS column entirely and have focused on counting the number of unique addresses. 

(I should remove the ENS column entirely from the raw data because it identifies people, will do that now actually).

Thanks again @baerlux

**Comment by PaulApivat** [comment]
@baerlux I've informed the POAP team of the data formatting issues.

I've also removed the ENS column entirely for all poap raw data.
